language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
install:
  - pip install coveralls
after_success: coveralls
before_script: wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: php mageekguy.atoum.phar -d tests
