site_name: Bantam
markdown_extensions: [admonition]
theme: readthedocs
pages:
- [index.md, Home]
- [prelim.md, Classes, Prelim]
- [role.md, Classes, Role]
- [validate.md, Classes, Validate]
- [event.md, Classes, Event]
- [i18n.md, Classes, I18N]
